# Generated by Django 3.2.6 on 2021-08-20 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-pk'], 'verbose_name': 'board', 'verbose_name_plural': 'boards'},
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='board'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='boards.board'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='topic'),
        ),
        migrations.DeleteModel(
            name='HistoricalBoard',
        ),
    ]
